name: stirling-app-dev
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 30 3 * * *

jobs:
  build:
    name: build
     env:    
      JOBENV: build
    runs-on: ubuntu-latest

    strategy:
      # fail-fast: false
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-18.04, ubuntu-latest]
        pypy: [pypy-3.7-v7.3.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Build
        run: python --version
  
  e1-deploy:
      name: e1-deploy
        run: python -c 'import math; print(math.factorial(5))'