name: stirling-app-dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    env:    
      JOBENV: build
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Build
      run: python --version
  
  e1-deploy:
    name: e1-deploy
    steps: 
    - name: deploy
      run: python -c 'import math; print(math.factorial(5))'